import type { LessonId } from "./types";

export type LessonCatalogItem = {
  id: LessonId;
  label: string;
  number: string;
  title: string;
  slug: string;
  routeModule: string;
  cliExampleModule: string;
  href: string;
  summary: string;
  meta: string;
  time: string;
  draft?: boolean | undefined;
};

export const lessons: readonly LessonCatalogItem[] = [
  {
    id: "my-first-query",
    label: "Lesson 01",
    number: "1",
    title: "My first query",
    slug: "my-first-query",
    routeModule: "routes/my-first-query.tsx",
    cliExampleModule: "my-first-query.sql.ts",
    href: "/lessons/my-first-query",
    summary:
      "Create a small table, seed two rows, SELECT them back, and inspect the plan Postgres uses.",
    meta: "SELECT · EXPLAIN",
    time: "10 min",
  },
  {
    id: "introduction-to-join",
    label: "Lesson 02",
    number: "2",
    title: "Introduction to JOIN",
    slug: "introduction-to-join",
    routeModule: "routes/introduction-to-join.tsx",
    cliExampleModule: "introduction-to-join.sql.ts",
    href: "/lessons/introduction-to-join",
    summary:
      "See why splitting data across tables matters, and use JOIN to combine it back together.",
    meta: "JOIN",
    time: "10 min",
  },
  {
    id: "schemas-tables-and-types",
    label: "Lesson 03",
    number: "3",
    title: "Schemas, tables, and types",
    slug: "schemas-tables-and-types",
    routeModule: "routes/schemas-tables-and-types.tsx",
    cliExampleModule: "schemas-tables-and-types.sql.ts",
    href: "/lessons/schemas-tables-and-types",
    summary:
      "Explore schemas, list tables, inspect columns, and understand database shape.",
    meta: "SCHEMA · TABLES · TYPES",
    time: "15 min",
  },
  {
    id: "introduction-to-indexes",
    label: "Lesson 04",
    number: "4",
    title: "An introduction to indexes",
    slug: "introduction-to-indexes",
    routeModule: "routes/introduction-to-indexes.tsx",
    cliExampleModule: "introduction-to-indexes.sql.ts",
    href: "/lessons/introduction-to-indexes",
    summary:
      "Indexes and EXPLAIN plans, comparing a sequential scan with an index scan on the same query.",
    meta: "INDEX · EXPLAIN",
    time: "15 min",
  },
  {
    id: "insert-update-delete",
    label: "Lesson 05",
    number: "5",
    title: "Insert, update, delete",
    slug: "insert-update-delete",
    routeModule: "routes/insert-update-delete.tsx",
    cliExampleModule: "insert-update-delete.sql.ts",
    href: "/lessons/insert-update-delete",
    summary: "Change stored rows with INSERT, UPDATE, DELETE, and RETURNING.",
    meta: "INSERT · UPDATE · DELETE",
    time: "15 min",
    draft: true,
  },
  {
    id: "constraints",
    label: "Lesson 06",
    number: "6",
    title: "Constraints",
    slug: "constraints",
    routeModule: "routes/constraints.tsx",
    cliExampleModule: "constraints.sql.ts",
    href: "/lessons/constraints",
    summary:
      "Use NOT NULL, UNIQUE, CHECK, primary keys, and foreign keys to protect data.",
    meta: "CONSTRAINTS · KEYS",
    time: "15 min",
    draft: true,
  },
  {
    id: "advanced-indexes",
    label: "Lesson 07",
    number: "7",
    title: "Advanced indexes",
    slug: "advanced-indexes",
    routeModule: "routes/advanced-indexes.tsx",
    cliExampleModule: "advanced-indexes.sql.ts",
    href: "/lessons/advanced-indexes",
    summary:
      "Use selectivity, composite indexes, and partial indexes to shape better plans.",
    meta: "SELECTIVITY · COMPOSITE · PARTIAL",
    time: "20 min",
    draft: true,
  },
  {
    id: "aggregation-intro",
    label: "Lesson 08",
    number: "8",
    title: "Aggregation intro",
    slug: "aggregation-intro",
    routeModule: "routes/aggregation-intro.tsx",
    cliExampleModule: "aggregation-intro.sql.ts",
    href: "/lessons/aggregation-intro",
    summary: "Summarize rows with COUNT, SUM, AVG, MIN, MAX, and GROUP BY.",
    meta: "COUNT · GROUP BY",
    time: "15 min",
    draft: true,
  },
  {
    id: "null",
    label: "Lesson 09",
    number: "9",
    title: "NULL",
    slug: "null",
    routeModule: "routes/null.tsx",
    cliExampleModule: "null.sql.ts",
    href: "/lessons/null",
    summary: "Understand missing values, IS NULL, three-valued logic, and COALESCE.",
    meta: "NULL · COALESCE",
    time: "15 min",
    draft: true,
  },
  {
    id: "joins",
    label: "Lesson 10",
    number: "10",
    title: "Types of JOINs",
    slug: "types-of-joins",
    routeModule: "routes/joins.tsx",
    cliExampleModule: "joins.sql.ts",
    href: "/lessons/types-of-joins",
    summary:
      "Compare INNER, LEFT, RIGHT, FULL OUTER, and CROSS JOIN on the same two tables.",
    meta: "JOIN · LEFT · RIGHT · FULL · CROSS",
    time: "20 min",
  },
  {
    id: "relationships",
    label: "Lesson 11",
    number: "11",
    title: "Relationships",
    slug: "relationships",
    routeModule: "routes/relationships.tsx",
    cliExampleModule: "relationships.sql.ts",
    href: "/lessons/relationships",
    summary: "Model one-to-many and many-to-many data with foreign keys and join tables.",
    meta: "FOREIGN KEY · RELATIONSHIPS",
    time: "20 min",
    draft: true,
  },
  {
    id: "sorting-and-pagination",
    label: "Lesson 12",
    number: "12",
    title: "Sorting and pagination",
    slug: "sorting-and-pagination",
    routeModule: "routes/sorting-and-pagination.tsx",
    cliExampleModule: "sorting-and-pagination.sql.ts",
    href: "/lessons/sorting-and-pagination",
    summary: "Sort rows deterministically with ORDER BY, LIMIT, OFFSET, and indexes.",
    meta: "ORDER BY · LIMIT",
    time: "15 min",
    draft: true,
  },
  {
    id: "text-search-basics",
    label: "Lesson 13",
    number: "13",
    title: "Text search basics",
    slug: "text-search-basics",
    routeModule: "routes/text-search-basics.tsx",
    cliExampleModule: "text-search-basics.sql.ts",
    href: "/lessons/text-search-basics",
    summary: "Search text with LIKE, ILIKE, wildcards, and case-insensitive patterns.",
    meta: "LIKE · ILIKE",
    time: "15 min",
    draft: true,
  },
  {
    id: "json-in-postgresql",
    label: "Lesson 14",
    number: "14",
    title: "JSON in PostgreSQL",
    slug: "json-in-postgresql",
    routeModule: "routes/json-in-postgresql.tsx",
    cliExampleModule: "json-in-postgresql.sql.ts",
    href: "/lessons/json-in-postgresql",
    summary: "Store jsonb, extract fields, query nested values, and use containment.",
    meta: "JSONB",
    time: "20 min",
    draft: true,
  },
  {
    id: "transactions",
    label: "Lesson 15",
    number: "15",
    title: "Transactions",
    slug: "transactions",
    routeModule: "routes/transactions.tsx",
    cliExampleModule: "transactions.sql.ts",
    href: "/lessons/transactions",
    summary: "Group changes with BEGIN, COMMIT, and ROLLBACK so work is atomic.",
    meta: "BEGIN · COMMIT · ROLLBACK",
    time: "15 min",
    draft: true,
  },
  {
    id: "advanced-aggregation",
    label: "Lesson 16",
    number: "16",
    title: "Advanced aggregation",
    slug: "advanced-aggregation",
    routeModule: "routes/advanced-aggregation.tsx",
    cliExampleModule: "advanced-aggregation.sql.ts",
    href: "/lessons/advanced-aggregation",
    summary: "Use HAVING, FILTER, date_trunc, and time-based grouping.",
    meta: "HAVING · FILTER · DATE_TRUNC",
    time: "20 min",
    draft: true,
  },
  {
    id: "vectors",
    label: "Lesson 17",
    number: "17",
    title: "Vectors",
    slug: "vectors",
    routeModule: "routes/vectors.tsx",
    cliExampleModule: "vectors.sql.ts",
    href: "/lessons/vectors",
    summary:
      "Use pgvector-style similarity search and see how vectors fit into PostgreSQL.",
    meta: "VECTOR · SIMILARITY",
    time: "20 min",
    draft: true,
  },
] as const satisfies readonly LessonCatalogItem[];

export const lessonSummaries = lessons.map(({ id, number, title, href }) => ({
  id,
  number,
  title,
  href,
}));
