import type { LessonId } from "./types";

export type LessonCatalogItem = {
  id: LessonId;
  label: string;
  number: string;
  title: string;
  slug: string;
  routeModule: string;
  cliExampleModule: string;
  href: string;
  summary: string;
  meta: string;
  time: string;
  draft?: boolean | undefined;
};

export const lessons: readonly LessonCatalogItem[] = [
  {
    id: "my-first-query",
    label: "Lesson 01",
    number: "1",
    title: "My first query",
    slug: "my-first-query",
    routeModule: "routes/my-first-query.tsx",
    cliExampleModule: "my-first-query.sql.ts",
    href: "/lessons/my-first-query",
    summary:
      "Create a small table, seed two rows, SELECT them back, and inspect the plan Postgres uses.",
    meta: "SELECT · EXPLAIN",
    time: "10 min",
  },
  {
    id: "introduction-to-join",
    label: "Lesson 02",
    number: "2",
    title: "Introduction to JOIN",
    slug: "introduction-to-join",
    routeModule: "routes/introduction-to-join.tsx",
    cliExampleModule: "introduction-to-join.sql.ts",
    href: "/lessons/introduction-to-join",
    summary:
      "See why splitting data across tables matters, and use JOIN to combine it back together.",
    meta: "JOIN",
    time: "10 min",
  },
  {
    id: "schemas-tables-and-types",
    label: "Lesson 03",
    number: "3",
    title: "Schemas, tables, and types",
    slug: "schemas-tables-and-types",
    routeModule: "routes/schemas-tables-and-types.tsx",
    cliExampleModule: "schemas-tables-and-types.sql.ts",
    href: "/lessons/schemas-tables-and-types",
    summary:
      "Explore schemas, list tables, inspect columns, and understand database shape.",
    meta: "SCHEMA · TABLES · TYPES",
    time: "15 min",
  },
  {
    id: "introduction-to-indexes",
    label: "Lesson 04",
    number: "4",
    title: "An introduction to indexes",
    slug: "introduction-to-indexes",
    routeModule: "routes/introduction-to-indexes.tsx",
    cliExampleModule: "introduction-to-indexes.sql.ts",
    href: "/lessons/introduction-to-indexes",
    summary:
      "Indexes and EXPLAIN plans, comparing a sequential scan with an index scan on the same query.",
    meta: "INDEX · EXPLAIN",
    time: "15 min",
  },
  {
    id: "insert-update-delete",
    label: "Lesson 05",
    number: "5",
    title: "Insert, update, delete, upsert",
    slug: "insert-update-delete",
    routeModule: "routes/insert-update-delete.tsx",
    cliExampleModule: "insert-update-delete.sql.ts",
    href: "/lessons/insert-update-delete",
    summary:
      "Change stored rows with INSERT, UPDATE, DELETE, RETURNING, and ON CONFLICT upserts.",
    meta: "INSERT · UPDATE · DELETE · UPSERT",
    time: "15 min",
  },
  {
    id: "mvcc",
    label: "Lesson 06",
    number: "6",
    title: "MVCC and row versions",
    slug: "mvcc",
    routeModule: "routes/mvcc.tsx",
    cliExampleModule: "mvcc.sql.ts",
    href: "/lessons/mvcc",
    summary:
      "Read the hidden xmin/xmax columns PostgreSQL keeps on every row, and watch them change across a real BEGIN ... COMMIT.",
    meta: "MVCC · XMIN · XMAX",
    time: "20 min",
  },
  {
    id: "constraints",
    label: "Lesson 07",
    number: "7",
    title: "Constraints",
    slug: "constraints",
    routeModule: "routes/constraints.tsx",
    cliExampleModule: "constraints.sql.ts",
    href: "/lessons/constraints",
    summary:
      "Use NOT NULL, UNIQUE, CHECK, primary keys, and foreign keys to protect data.",
    meta: "CONSTRAINTS · KEYS",
    time: "15 min",
    draft: true,
  },
  {
    id: "advanced-indexes",
    label: "Lesson 08",
    number: "8",
    title: "Advanced indexes",
    slug: "advanced-indexes",
    routeModule: "routes/advanced-indexes.tsx",
    cliExampleModule: "advanced-indexes.sql.ts",
    href: "/lessons/advanced-indexes",
    summary:
      "Use selectivity, composite indexes, and partial indexes to shape better plans.",
    meta: "SELECTIVITY · COMPOSITE · PARTIAL",
    time: "20 min",
    draft: true,
  },
  {
    id: "aggregation-intro",
    label: "Lesson 09",
    number: "9",
    title: "Aggregation intro",
    slug: "aggregation-intro",
    routeModule: "routes/aggregation-intro.tsx",
    cliExampleModule: "aggregation-intro.sql.ts",
    href: "/lessons/aggregation-intro",
    summary: "Summarize rows with COUNT, SUM, AVG, MIN, MAX, and GROUP BY.",
    meta: "COUNT · GROUP BY",
    time: "15 min",
    draft: true,
  },
  {
    id: "null",
    label: "Lesson 10",
    number: "10",
    title: "NULL",
    slug: "null",
    routeModule: "routes/null.tsx",
    cliExampleModule: "null.sql.ts",
    href: "/lessons/null",
    summary: "Understand missing values, IS NULL, three-valued logic, and COALESCE.",
    meta: "NULL · COALESCE",
    time: "15 min",
    draft: true,
  },
  {
    id: "joins",
    label: "Lesson 11",
    number: "11",
    title: "Types of JOINs",
    slug: "types-of-joins",
    routeModule: "routes/joins.tsx",
    cliExampleModule: "joins.sql.ts",
    href: "/lessons/types-of-joins",
    summary:
      "Compare INNER, LEFT, RIGHT, FULL OUTER, and CROSS JOIN on the same two tables.",
    meta: "JOIN · LEFT · RIGHT · FULL · CROSS",
    time: "20 min",
  },
  {
    id: "relationships",
    label: "Lesson 12",
    number: "12",
    title: "Relationships",
    slug: "relationships",
    routeModule: "routes/relationships.tsx",
    cliExampleModule: "relationships.sql.ts",
    href: "/lessons/relationships",
    summary: "Model one-to-many and many-to-many data with foreign keys and join tables.",
    meta: "FOREIGN KEY · RELATIONSHIPS",
    time: "20 min",
    draft: true,
  },
  {
    id: "sorting-and-pagination",
    label: "Lesson 13",
    number: "13",
    title: "Sorting and pagination",
    slug: "sorting-and-pagination",
    routeModule: "routes/sorting-and-pagination.tsx",
    cliExampleModule: "sorting-and-pagination.sql.ts",
    href: "/lessons/sorting-and-pagination",
    summary: "Sort rows deterministically with ORDER BY, LIMIT, OFFSET, and indexes.",
    meta: "ORDER BY · LIMIT",
    time: "15 min",
    draft: true,
  },
  {
    id: "text-search-basics",
    label: "Lesson 14",
    number: "14",
    title: "Text search basics",
    slug: "text-search-basics",
    routeModule: "routes/text-search-basics.tsx",
    cliExampleModule: "text-search-basics.sql.ts",
    href: "/lessons/text-search-basics",
    summary: "Search text with LIKE, ILIKE, wildcards, and case-insensitive patterns.",
    meta: "LIKE · ILIKE",
    time: "15 min",
    draft: true,
  },
  {
    id: "json-in-postgresql",
    label: "Lesson 15",
    number: "15",
    title: "JSON in PostgreSQL",
    slug: "json-in-postgresql",
    routeModule: "routes/json-in-postgresql.tsx",
    cliExampleModule: "json-in-postgresql.sql.ts",
    href: "/lessons/json-in-postgresql",
    summary: "Store jsonb, extract fields, query nested values, and use containment.",
    meta: "JSONB",
    time: "20 min",
    draft: true,
  },
  {
    id: "transactions",
    label: "Lesson 16",
    number: "16",
    title: "Transactions",
    slug: "transactions",
    routeModule: "routes/transactions.tsx",
    cliExampleModule: "transactions.sql.ts",
    href: "/lessons/transactions",
    summary: "Group changes with BEGIN, COMMIT, and ROLLBACK so work is atomic.",
    meta: "BEGIN · COMMIT · ROLLBACK",
    time: "15 min",
    draft: true,
  },
  {
    id: "advanced-aggregation",
    label: "Lesson 17",
    number: "17",
    title: "Advanced aggregation",
    slug: "advanced-aggregation",
    routeModule: "routes/advanced-aggregation.tsx",
    cliExampleModule: "advanced-aggregation.sql.ts",
    href: "/lessons/advanced-aggregation",
    summary: "Use HAVING, FILTER, date_trunc, and time-based grouping.",
    meta: "HAVING · FILTER · DATE_TRUNC",
    time: "20 min",
    draft: true,
  },
  {
    id: "vectors",
    label: "Lesson 18",
    number: "18",
    title: "Vectors and similarity search",
    slug: "vectors",
    routeModule: "routes/vectors.tsx",
    cliExampleModule: "vectors.sql.ts",
    href: "/lessons/vectors",
    summary:
      "Search by meaning: embeddings, L2 distance, cosine similarity, and nearest neighbours, computed by hand with plain arrays.",
    meta: "EMBEDDINGS · DISTANCE · SIMILARITY",
    time: "20 min",
    draft: true,
  },
  {
    id: "pgvector",
    label: "Lesson 19",
    number: "19",
    title: "pgvector",
    slug: "pgvector",
    routeModule: "routes/pgvector.tsx",
    cliExampleModule: "pgvector.sql.ts",
    href: "/lessons/pgvector",
    summary:
      "The vectors lesson again, with pgvector: a real vector type, distance operators, and four ways to search many rows: exact, HNSW, IVFFlat, and smaller vectors.",
    meta: "PGVECTOR · HNSW · IVFFLAT · HALFVEC",
    time: "20 min",
    draft: true,
  },
  {
    id: "full-text-search",
    label: "Lesson 20",
    number: "20",
    title: "Full-text search",
    slug: "full-text-search",
    routeModule: "routes/full-text-search.tsx",
    cliExampleModule: "full-text-search.sql.ts",
    href: "/lessons/full-text-search",
    summary:
      "Search words instead of characters with tsvector and tsquery: stemming, search-box syntax, ranking, highlights, and a GIN index.",
    meta: "TSVECTOR · TSQUERY · GIN",
    time: "20 min",
    draft: true,
  },
  {
    id: "fuzzy-search",
    label: "Lesson 21",
    number: "21",
    title: "Fuzzy search with pg_trgm",
    slug: "fuzzy-search",
    routeModule: "routes/fuzzy-search.tsx",
    cliExampleModule: "fuzzy-search.sql.ts",
    href: "/lessons/fuzzy-search",
    summary:
      "Find text despite typos with trigram similarity, word_similarity, 'did you mean' suggestions, and trigram indexes.",
    meta: "PG_TRGM · SIMILARITY",
    time: "20 min",
    draft: true,
  },
  {
    id: "text-search-in-postgres",
    label: "Lesson 22",
    number: "22",
    title: "Text search in Postgres, without Elasticsearch or Algolia",
    slug: "text-search-in-postgres",
    routeModule: "routes/text-search-in-postgres.tsx",
    cliExampleModule: "text-search-in-postgres.sql.ts",
    href: "/lessons/text-search-in-postgres",
    summary:
      "Compare ILIKE, fuzzy, full-text, semantic, and hybrid search on the same documents, and decide when Postgres is enough.",
    meta: "ILIKE · PG_TRGM · TSVECTOR · PGVECTOR",
    time: "20 min",
    draft: true,
  },
  {
    id: "concurrency-reservation-system",
    label: "Lesson 23",
    number: "23",
    title: "Implementing a high-concurrency system with Postgres",
    slug: "concurrency-reservation-system",
    routeModule: "routes/concurrency-reservation-system.tsx",
    cliExampleModule: "concurrency-reservation-system.sql.ts",
    href: "/lessons/concurrency-reservation-system",
    summary:
      "Model a seat reservation system and use transactions with advisory locks to close a real race condition.",
    meta: "ACID · TRANSACTIONS · ADVISORY LOCKS",
    time: "25 min",
  },
  {
    id: "transaction-isolation-levels",
    label: "Lesson 24",
    number: "24",
    title: "Transaction isolation levels",
    slug: "transaction-isolation-levels",
    routeModule: "routes/transaction-isolation-levels.tsx",
    cliExampleModule: "transaction-isolation-levels.sql.ts",
    href: "/lessons/transaction-isolation-levels",
    summary:
      "See what READ COMMITTED, REPEATABLE READ, and SERIALIZABLE actually let concurrent transactions see, with a bug only SERIALIZABLE catches.",
    meta: "ISOLATION LEVELS · WRITE SKEW",
    time: "20 min",
  },
  {
    id: "postgres-locks",
    label: "Lesson 25",
    number: "25",
    title: "Locks",
    slug: "postgres-locks",
    routeModule: "routes/postgres-locks.tsx",
    cliExampleModule: "postgres-locks.sql.ts",
    href: "/lessons/postgres-locks",
    summary:
      "See which locks every statement takes, what blocks what, and how NOWAIT, SKIP LOCKED, and lock_timeout keep sessions from waiting forever.",
    meta: "TABLE LOCKS · ROW LOCKS · SKIP LOCKED",
    time: "25 min",
    draft: true,
  },
  {
    id: "slow-queries",
    label: "Lesson 26",
    number: "26",
    title: "Finding and fixing slow queries",
    slug: "slow-queries",
    routeModule: "routes/slow-queries.tsx",
    cliExampleModule: "slow-queries.sql.ts",
    href: "/lessons/slow-queries",
    summary:
      "Profile an app's queries with pg_stat_statements, find why the slowest are slow with EXPLAIN ANALYZE, and fix them with a trigram index and keyset pagination.",
    meta: "PG_STAT_STATEMENTS · EXPLAIN ANALYZE · PG_TRGM",
    time: "25 min",
    draft: true,
  },
  {
    id: "postgres-job-queue",
    label: "Lesson 27",
    number: "27",
    title: "Building a job queue with Postgres",
    slug: "postgres-job-queue",
    routeModule: "routes/postgres-job-queue.tsx",
    cliExampleModule: "postgres-job-queue.sql.ts",
    href: "/lessons/postgres-job-queue",
    summary:
      "Build a job queue on a plain table: hand each job to one of many workers with SKIP LOCKED, survive crashes with leases and retries, and see why exactly-once delivery is impossible but exactly-once processing isn't.",
    meta: "SKIP LOCKED · DELIVERY GUARANTEES · OUTBOX",
    time: "30 min",
    draft: true,
  },
] as const satisfies readonly LessonCatalogItem[];

export const lessonSummaries = lessons.map(({ id, number, title, href }) => ({
  id,
  number,
  title,
  href,
}));
